# Generated by Django 3.1.3 on 2020-11-25 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'custom_requests_assignedroles',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('usr', 'user'), ('opr', 'operator'), ('adm', 'admin')], default='usr', help_text='Select user role', max_length=20)),
            ],
            options={
                'verbose_name': 'User role',
                'verbose_name_plural': 'User roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter the text of your application', max_length=100)),
                ('status', models.CharField(choices=[('drf', 'draft'), ('snt', 'sent'), ('acc', 'accepted'), ('rej', 'rejected')], default='drf', editable=False, help_text='Select requests status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User request',
                'verbose_name_plural': 'User requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(through='custom_requests.AssignedRoles', to='custom_requests.UserRoles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extending User info',
                'verbose_name_plural': 'Extending User info',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='assignedroles',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_requests.userroles'),
        ),
        migrations.AddField(
            model_name='assignedroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_requests.extendinguser'),
        ),
    ]
