# Generated by Django 3.1.3 on 2020-11-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'User request', 'verbose_name_plural': 'User requests'},
        ),
    ]
